name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      rabbitmq-streaming:
        image: pivotalrabbitmq/rabbitmq-stream
        env:
          RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_stream"
        ports:
          - 5551:5551
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Run coverage
      run:  go test -v  ./pkg/streaming -race -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: gsantomaggio/go-streaming-client:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}