name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      rabbitmq-streaming:
        image: pivotalrabbitmq/rabbitmq-stream
          env:
            RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_stream"
          ports:
            - 5551:5551
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...

    - name: Run coverage
      run:  go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage to Codecov
      run: bash <(curl -s https://codecov.io/bash)
